version: "2"
services:
  sample_website:
    build: .
    container_name: sample_website
    hostname: sample_website
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    restart: unless-stopped